<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_offset_z" value="0.01"/>
  <xacro:property name="caster_wheel_radius" value="0.01"/>
  <xacro:property name="caster_wheel_mass" value="0.01"/>
  <xacro:property name="caster_wheel_offset_x" value="0.075"/>
  <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>


  <link name="imu_link"/>
  <link
    name="base_link">
    <inertial>
      <origin
        xyz="-0.014025 -0.00011707 0.082168"
        rpy="0 0 0" />
      <mass
        value="0.52447" />
      <inertia
        ixx="0.00066245"
        ixy="-3.1852E-08"
        ixz="-4.6503E-05"
        iyy="0.0012486"
        iyz="-3.356E-08"
        izz="0.0018052" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/base_link.STL" /> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/base_link.STL"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0 0.62745 0.23529 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/base_link.STL" /> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/base_link.STL"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  <link
    name="back_right_link">
    <inertial>
      <origin
        xyz="3.8959E-08 0.0015615 -6.3774E-08"
        rpy="0 0 0" />
      <mass
        value="0.060236" />
      <inertia
        ixx="2.5326E-05"
        ixy="-2.701E-10"
        ixz="3.3546E-09"
        iyy="4.4342E-05"
        iyz="-2.9324E-10"
        izz="2.531E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/back_right_link.STL"/> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/back_right_link.STL"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/back_right_link.STL" /> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/back_right_link.STL"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="back_right_joint"
    type="continuous">
    <origin
      xyz="-0.11607 -0.08425 0.0125"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="back_right_link" />
    <axis
      xyz="0 1 0" />
    <!-- <dynamics damping="0.2" friction="0.2"/> -->
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </joint>
  <link
    name="back_left_link">
    <inertial>
      <origin
        xyz="-6.87042718550135E-08 -0.00156153690070754 3.00324059371304E-08"
        rpy="0 0 0" />
      <mass
        value="0.0602360431220635" />
      <inertia
        ixx="2.53100986719244E-05"
        ixy="-3.65138701967536E-11"
        ixz="1.15601374112124E-09"
        iyy="4.43431918315874E-05"
        iyz="-7.01985398840287E-11"
        izz="2.53280330627738E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/back_right_link.STL" /> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/back_right_link.STL"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/back_right_link.STL" /> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/back_right_link.STL"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="back_left_joint"
    type="continuous">
    <origin
      xyz="-0.11607 0.08425 0.0125"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="back_left_link" />
    <axis
      xyz="0 1 0" />
    <!-- <dynamics damping="0.2" friction="0.2"/> -->
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </joint>

  <link
    name="camera_link">
    <inertial>
      <origin
        xyz="-0.0022507 -5.8908E-06 -0.021168"
        rpy="0 0 0" />
      <mass
        value="0.22414" />
      <inertia
        ixx="0.00039172"
        ixy="2.2482E-08"
        ixz="4.3677E-08"
        iyy="4.6625E-05"
        iyz="1.3858E-10"
        izz="0.0004106" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/camera_link.STL" /> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/camera_link.STL"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.082353 0.082353 0.082353 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <!-- <mesh filename="/home/suleman/dev_ws/src/articubot_one/description/meshes/Ackermann/camera_link.STL" /> -->
        <mesh filename="file://$(find articubot_one)/description/meshes/Ackermann/camera_link.STL"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="camera_joint"
    type="fixed">
    <origin
      xyz="0.095117 0 0.09955"
      rpy="0 0.0057171 0" />
    <parent
      link="base_link" />
    <child
      link="camera_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  

  <joint name="base_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.05 0.0 0.05" rpy="0 3.1415 1.5707"/>
  </joint>

  

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 0.0215" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint"/>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.145 0 0"/>
    <!-- <dynamics damping="0.2" friction="0.2"/> -->
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </joint>


  <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.01" />
      <inertia ixx="1.6e-6" ixy="0" ixz="0" iyy="1.6e-6" iyz="0" izz="1.6e-6"/>
    </inertial>
  </link>
 
  <gazebo reference="caster_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.2"/>
    <mu2 value="0.2"/>
  </gazebo>
 




  <!--transmission name="front_right_steer_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_right_steer_joint" >
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="front_right_steer_joint_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>100</motorTorqueConstant>
    </actuator>
  </transmission>  
  
  <transmission name="front_left_steer_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_left_steer_joint" >
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="front_left_steer_joint_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>100</motorTorqueConstant>
    </actuator>
  </transmission>
 <transmission name="back_right_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_right_joint" >
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="back_right_joint_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>      
  
  <transmission name="back_left_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_left_joint" >
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="back_right_left_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission-->

</robot>
